---
- name: Gather variables for each OS
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- name: register etcd_bind_address
  set_fact:
    _etcd_address: "{{ etcd_bind_address }}"

- include_tasks: install.yml
  tags:
    - etcd-install

- include_tasks: post_install.yml
  tags:
    - etcd-config
...
